### ISSUE TITLE
Why did you keep audio files in wav format?

### ISSUE THREAD

**Issue by rvencu** [audio-captioning/clotho-dataset#2]
I am curious if there was any reason or you did not care about audio files format.

I am considering creating a large scale audio dataset by training a small model that later I can use to filter millions of samples and file format seems sensible to be as compressed as possible to save storage space.

**Comment by dr-costas** [comment]
> I am curious if there was any reason or you did not care about audio files format.

I'm sorry, but I cannot see how the above is a) productive, b) deducted from the repo. I mean, how one can actually infer that other people that spend time for something, did not **care** about audio files format. Then, I cannot see how such a passive-aggressive question will benefit either of the conversing parties, actually implying that ones selection was a-priori deemed as wrong. 

> I am considering creating a large scale audio dataset by training a small model that later I can use to filter millions of samples and file format seems sensible to be as compressed as possible to save storage space.

Well done, but I do not feel OK to help or answer someone that tries to flash-bank using the above. Good luck with your endeavours.
